<?php

return [
    'COLEGIO NACIONAL "RAFAEL HERNÁNDEZ"'=>'COLEGIO NACIONAL "RAFAEL HERNÁNDEZ"','LICEO VÍCTOR MERCANTE'=>'LICEO VÍCTOR MERCANTE','BACHILLERATO DE BELLAS ARTES "PROF. FRANCISCO A. DE SANTO"'=>'BACHILLERATO DE BELLAS ARTES "PROF. FRANCISCO A. DE SANTO"','ESCUELA GRADUADA "JOAQUÍN V. GONZÁLEZ" (ANEXA)'=>'ESCUELA GRADUADA "JOAQUÍN V. GONZÁLEZ" (ANEXA)','ESCUELA DE AGRICULTURA Y GANADERÍA "M.C. Y M.L. INCHAUSTI"'=>'ESCUELA DE AGRICULTURA Y GANADERÍA "M.C. Y M.L. INCHAUSTI"',
];


